{
  bubblewrap ? null,
  importNpmLock,
  lib,
  nodejs,
  nono,
  stdenvNoCC,
}:

let
  source = ../extensions/sandbox;
  nodeModules = importNpmLock.buildNodeModules {
    npmRoot = source;
    inherit nodejs;
  };
in
stdenvNoCC.mkDerivation {
  pname = "pi-sandbox-extension";
  version = "3.0.0";

  src = source;

  installPhase = ''
    runHook preInstall
    mkdir -p $out
    for sourceFile in *.ts; do
      case "$sourceFile" in
        *.test.ts | test-setup.ts) continue ;;
      esac
      cp "$sourceFile" "$out/"
    done
    cp package.json package-lock.json $out/
    cp -R ${nodeModules}/node_modules "$out/"
    chmod -R u+w "$out/node_modules"
    cat > $out/fixed-executables.ts <<'EOF'
    /** Fixed Nix-store executables generated by nix/pi-sandbox-extension.nix. */
    export const FIXED_NONO_PATH: string | null = "${nono}/bin/nono";
    export const FIXED_BWRAP_PATH: string | null = "${if bubblewrap == null then "" else lib.getExe bubblewrap}";
    EOF
    runHook postInstall
  '';

  meta = {
    description = "Pi sandbox policy adapter backed by nono";
    license = lib.licenses.mit;
    platforms = lib.platforms.darwin ++ lib.platforms.linux;
  };
}
